ds92ko/unit-mate

- package.json
- src/components/ToggleButton/index.css.ts
> STAGE 배포 테스트

- src/stores/themeStore.ts
<br/>
- 전역 상태를 localStorage에 저장하여 새로고침 시 유지되도록 구현
<br/>
<br/>
> feat: themeStore에 persist middleware 추가

- src/components/Bookmark/index.css.ts
- src/components/Bookmark/index.tsx
- src/components/Keyboard/index.css.ts
- src/components/Main/index.css.ts
- src/components/Main/index.tsx
- src/components/Result/index.css.ts
- src/components/Result/index.tsx
- src/components/ToggleButton/index.tsx
- src/components/ToggleButton/type.tsx
<br/>
- #21 
<br/>
- Result, Bookmark 토글 기능 구현
- main 중복 태그 수정
- 레이아웃 버그 수정
<br/>
<br/>
> feat: 토글 기능 구현 및 레이아웃 수정

- src/components/Router.tsx
- src/components/layouts/Gnb/index.tsx
- src/data/routes.ts
<br/>
- 라우터 데이터 및 컴포넌트 리팩토링
<br/>
<br/>
> refactor: router 데이터 및 Router 컴포넌트 리팩토링

- src/components/GuideInfo/index.css.ts
- src/components/GuideInfo/index.tsx
- src/components/History/index.css.ts
- src/components/History/index.tsx
<br/>
- #
<br/>
- 에러 페이지 테마 적용
- 북마크 아이콘 적용
<br/>
<br/>
> chore: 에러 페이지 테마 적용 & 북마크 아이콘 적용

- src/components/Bookmark/index.tsx
- src/components/GuideInfo/index.css.ts
- src/components/GuideInfo/index.tsx
- src/components/GuideInfo/type.tsx
- src/components/Input/index.css.ts
- src/components/Input/index.tsx
- src/components/Result/index.css.ts
- src/components/Result/index.tsx
- src/pages/InternalServerError/index.tsx
- src/pages/NotFound/index.tsx
- src/styles/layout.css.ts
- src/styles/reset.css.ts
<br/>
- #
<br/>
- Input 컴포넌트 제작
- navigate 삼항 연산자로 변경
<br/>
PR에 참고할만한 사항이 있을 경우 작성해주세요.
-
<br/>
<br/>
> feat: input 컴포넌트 제작

- src/components/Bookmark/index.tsx
- src/components/History/index.tsx
- src/components/History/type.tsx
- src/pages/Basic/index.tsx
- src/stores/historyStore.ts
<br/>
- #
<br/>
- bookmark 구조 변경
<br/>
PR에 참고할만한 사항이 있을 경우 작성해주세요.
-
<br/>
<br/>
> refactor: bookmark 구조 변경

- src/App.tsx
- src/components/Bookmark/index.css.ts
- src/components/Input/index.tsx
- src/components/KeyButton/index.css.ts
- src/components/Keyboard/index.css.ts
- src/components/Layout.tsx
- src/components/Main/index.css.ts
- src/components/Result/index.css.ts
- src/components/Result/index.tsx
- src/components/layouts/Gnb/index.css.ts
- src/components/layouts/Header/index.css.ts
- src/components/layouts/Theme/index.css.ts
- src/styles/global.css.ts
- src/styles/layout.css.ts
<br/>
- layout 스타일 수정
- input placeholder 문구 수정
- 결과 추가 시 스크롤 최하단 이동
<br/>
<br/>
> 레이아웃 스타일 수정 및 결과 추가 시 스크롤 최하단 기능 추가

- src/components/Keyboard/index.tsx
- src/stores/calcStore.ts
- src/stores/historyStore.ts
<br/>
- viewport 계산 기능 추가
<br/>
<br/>
> feat: viewport 계산 기능 추가

- src/components/Keyboard/index.tsx
- src/stores/calcStore.ts
- src/stores/historyStore.ts
<br/>
- rem&em 계산 기능 추가
<br/>
<br/>
> feat: rem&em 계산 기능 추가

- package-lock.json
- package.json
- src/components/Keyboard/index.css.ts
- src/components/Keyboard/index.tsx
- src/stores/calcStore.ts
- src/stores/historyStore.ts
<br/>
- 일반 계산기 누락된 키 추가
- 일반 계산기 기능 추가
<br/>
<br/>
> 일반 계산기 기능 추가

- src/components/History/index.tsx
- src/stores/historyStore.ts
<br/>
- bookmark 기능 추가
<br/>
<br/>
> feat: bookmark 기능 추가

- src/components/KeyButton/index.css.ts
- src/components/KeyButton/index.tsx
- src/components/Keyboard/index.tsx
<br/>
- key 이벤트 추가
<br/>
<br/>
> feat: key 이벤트 추가

- src/components/Keyboard/index.css.ts
<br/>
- basic 키보드 레이아웃 스타일 변경
<br/>
<br/>
> fix: basic 키보드 레이아웃 스타일 변경

- src/components/History/index.css.ts
- src/components/History/index.tsx
- vercel.json
<br/>
- #57 
<br/>
- 결과값 클릭 시 단위, = 제외하고 값 복사 기능 추가
<br/>
<br/>
> feat: 결과값 복사 기능 추가

- src/components/layouts/Header/index.tsx
<br/>
- #64 
<br/>
- 로고 클릭 시 메인 페이지로 이동 기능 추가
<br/>
<br/>
> feat: 로고 링크 연결 추가

- src/components/Input/index.css.ts
<br/>
- #60 
<br/>
- placeholder 색상 미적용 이슈 수정
<br/>
<br/>
> fix: placeholder 버그 수정

- src/components/Input/index.tsx
<br/>
- #66 
<br/>
- input autoFocus 추가
<br/>
<br/>
> feat: input autoFocus 추가

- src/components/Keyboard/index.tsx
- src/stores/calcStore.ts
- vercel.json
<br/>
- #65 
<br/>
-백스페이스 키 누르면 1글자씩 지워지는 기능 추가
<br/>
PR에 참고할만한 사항이 있을 경우 작성해주세요.
-keyboard 함수를 useEffect 밖에 정의하였을때, 해당 함수는 useEffect의 의존성 배열에 포함되지 않아서 ESLint 경고가 발생하는  이슈가 있었습니다. 함수를 useEffect 내부에 정의하면 매 렌더링마다 함수가 재생성되므로 성능에 영향을 줄 수 있지만  ESLint 경고를 해결할 수 있었습니다.
<br/>
<br/>
> feat: backspace 키보드 기능 추가

- src/components/Bookmark/index.css.ts
<br/>
- #61 
<br/>
- Bookmark 리스트가 늘어나면 자동으로 스크롤 바가 생성되도록 스타일 수정
<br/>
<br/>
> fix: bookmark 스크롤 영역 스타일 수정

- src/stores/themeStore.ts
<br/>
- #71 
<br/>
- 다크/라이트 모드 변경 시 테마 컬러 유지
<br/>
<br/>
> feat: 다크/라이트 모드 변경 시 테마 컬러 유지

- src/components/History/index.css.ts
<br/>
- #80 
<br/>
- 계산 결과가 길어질 경우, word-break 처리
<br/>
<br/>
> fix: 계산 결과 word-break 처리

- src/components/Input/index.tsx
<br/>
- #66 
<br/>
- input cursor side effect 수정
<br/>
<br/>
> fix: input cursor side effect 수정
